name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.0
        with:
          file: ./kube-news/src/Dockerfile
          context: ./kube-news/src/
          push: true
          tags: |
            davigdc/kube-news:latest
            davigdc/kube-news:${{github.run_number}}
            
  CD:
    runs-on: ubuntu-latest 
    needs: [CI]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_KUBECONFIG}}

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.3
        with:
          images: |
            davigdc/kube-news:${{github.run_number}}
          manifests: |
            ./kube-news/k8s/deployment.yaml
