name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest 

    steps:
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.0
        with:
          file: ./kube-news/src/Dockerfile
          context: ./kube-news/src/
          push: true
          tags: |
            davigdc/kube-news:latest
            davigdc/kube-news:${{github.run_number}}
